steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/ottawarec/ottawarec:latest
      - .
images:
  - gcr.io/ottawarec/ottawarec:latest
options:
  logging: GCS_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
